version: '3'
services:
    web:
        tty: true
        stdin_open: true
        build: 
            context: .             # where is the root folder
            dockerfile: Dockerfile.dev   # location of docker file
        ports: 
            - "3000:3000"          # map local port 3000 to docker port 3000
        volumes:
            - /app/node_modules    # do not try and map folder to /app/node_modules
            - .:/app               # map current folder outside container to app folder in container
    tests:
        tty: true
        stdin_open: true
        build: 
            context: .             # where is the root folder
            dockerfile: Dockerfile.dev   # location of docker file
        volumes:
            - /app/node_modules    # do not try and map folder to /app/node_modules
            - .:/app               # map current folder outside container to app folder in container
        command: [ "npm", "run", "test"]  #override start command


